import { useMemo, useState, useEffect } from 'react';
import KPICard from '../components/dashboard/KPICard';
import ChartPlaceholder from '../components/dashboard/ChartPlaceholder';
import DynamicChart from '../components/dashboard/DynamicChart';
import SummaryCard from '../components/dashboard/SummaryCard';
import ColumnSelector from '../components/dashboard/ColumnSelector';
import ChatPanel from '../components/chat/ChatPanel';
import { SkeletonKPICard, SkeletonChart } from '../components/ui/Skeleton';
import { computeKPIs, pickPrimaryColumn, getNumericColumns } from '../utils/kpi';
import type { ParsedDataset, SummaryState, AIChartSpec } from '../types/dashboard';

const EMPTY_KPIS = [
  { id: 'k1', label: 'Average',       value: '—', change: '—', trend: 'neutral' as const, subLabel: 'Upload data' },
  { id: 'k2', label: 'Range',         value: '—', change: '—', trend: 'neutral' as const, subLabel: 'Upload data' },
  { id: 'k3', label: 'Std Deviation', value: '—', change: '—', trend: 'neutral' as const, subLabel: 'Upload data' },
  { id: 'k4', label: 'Growth',        value: '—', change: '—', trend: 'neutral' as const, subLabel: 'Upload data' },
];

interface DashboardPageProps {
  dataset: ParsedDataset | null;
  summaryState: SummaryState;
  charts: AIChartSpec[];
}

export default function DashboardPage({ dataset, summaryState, charts }: DashboardPageProps) {
  const [selectedCol, setSelectedCol] = useState<string | null>(null);

  useEffect(() => {
    if (dataset) setSelectedCol(pickPrimaryColumn(dataset));
    else setSelectedCol(null);
  }, [dataset]);

  const numericCols = useMemo(() => (dataset ? getNumericColumns(dataset) : []), [dataset]);

  const kpis = useMemo(
    () => (dataset ? computeKPIs(dataset, selectedCol ?? undefined) : EMPTY_KPIS),
    [dataset, selectedCol],
  );

  const isAnalyzing = summaryState.status === 'loading';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', padding: '24px' }}>

      {/* KPI header row */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <h2 style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)', margin: 0 }}>Key Metrics</h2>
          <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>Computed locally from your dataset</p>
        </div>
        {dataset && numericCols.length > 1 && selectedCol && (
          <ColumnSelector
            columns={numericCols}
            selected={selectedCol}
            onChange={setSelectedCol}
          />
        )}
      </div>

      {/* KPI cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '14px' }}
        className="lg:grid-cols-4"
      >
        {isAnalyzing && !dataset
          ? Array.from({ length: 4 }).map((_, i) => <SkeletonKPICard key={i} />)
          : kpis.map((kpi) => <KPICard key={kpi.id} data={kpi} />)
        }
      </div>

      {/* Divider */}
      <div style={{ height: '1px', background: 'var(--border)', margin: '0 -2px' }} />

      {/* AI Analysis header */}
      <div>
        <h2 style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)', margin: 0 }}>AI Analysis</h2>
        <p style={{ fontSize: '11px', color: 'var(--text-muted)', margin: 0 }}>Charts and summary generated by Gemini 2.5 Flash</p>
      </div>

      {/* First chart + Summary */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '20px' }}
        className="xl:grid-cols-3"
      >
        <div className="xl:col-span-2">
          {isAnalyzing ? (
            <SkeletonChart height={340} />
          ) : dataset && charts.length > 0 ? (
            <DynamicChart dataset={dataset} spec={charts[0]} height={340} colorIndex={0} />
          ) : (
            <ChartPlaceholder title="Price / Performance Chart" height={340} />
          )}
        </div>
        <div className="xl:col-span-1">
          <SummaryCard summaryState={summaryState} fileName={dataset?.fileName ?? 'summary'} />
        </div>
      </div>

      {/* Remaining charts */}
      {isAnalyzing && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(1,1fr)', gap: '20px' }} className="lg:grid-cols-2">
          <SkeletonChart height={260} />
          <SkeletonChart height={260} />
        </div>
      )}

      {!isAnalyzing && charts.length > 1 && dataset && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(1,1fr)', gap: '20px' }} className="lg:grid-cols-2">
          {charts.slice(1).map((spec, i) => (
            <DynamicChart key={`${spec.title}-${i}`} dataset={dataset} spec={spec} height={280} colorIndex={i + 1} />
          ))}
        </div>
      )}

      {!isAnalyzing && charts.length === 0 && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(1,1fr)', gap: '20px' }} className="lg:grid-cols-2">
          <ChartPlaceholder title="Volume Analysis" height={260} />
          <ChartPlaceholder title="Distribution Breakdown" height={260} />
        </div>
      )}

      {/* Divider */}
      <div style={{ height: '1px', background: 'var(--border)', margin: '0 -2px' }} />

      {/* Chat */}
      <div>
        <h2 style={{ fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)', margin: '0 0 16px' }}>Data Assistant</h2>
        <ChatPanel dataset={dataset} />
      </div>

    </div>
  );
}
