import jsPDF from 'jspdf';

export function exportSummaryPdf(summary: string, fileName: string): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  // Header
  doc.setFillColor(10, 14, 26);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(74, 158, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Financial Dashboard', margin, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(143, 163, 191);
  doc.text('AI Analysis Summary', margin, 26);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), margin, 33);

  // Dataset label
  doc.setTextColor(74, 96, 128);
  doc.setFontSize(8);
  doc.text(`Source: ${fileName}`, margin, 52);

  // Divider
  doc.setDrawColor(30, 45, 71);
  doc.line(margin, 56, pageWidth - margin, 56);

  // Summary heading
  doc.setTextColor(232, 237, 245);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, 66);

  // Summary body
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(200, 216, 232);
  const lines = doc.splitTextToSize(summary, maxWidth);
  doc.text(lines, margin, 76);

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(8);
  doc.setTextColor(74, 96, 128);
  doc.text('Generated by AI Financial Dashboard · Powered by Gemini 2.5 Flash', margin, footerY);

  doc.save(`${fileName.replace(/\.[^.]+$/, '')}_summary.pdf`);
}
